# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np
arr = np.random.uniform(0, 20, (4, 7)) #генерация случайного массива 
min_1 = np.min(arr)  #находим минимальное и максимальное значение 
max_1 = np.max(arr)

a = 1.0 - (max_1 - min_1)
b = -a * min_1
normalized_arr = a * arr + b


print("Исходный массив:", arr)

print("Нормализированный массив:", normalized_arr)



Исходный массив: [[12.29917286 15.64523494 18.09683809 12.80770281 18.74649447  0.23286292
   1.88746263]
 [ 8.03470841  1.71993149  1.44572051  3.36014855  6.32047057 19.38670856
   3.81235223]
 [18.13830187  0.67378768 15.41573827  8.51014737 18.474155   12.01215784
  16.80641257]
 [16.34888078 18.45655561  5.33205584 10.83350658 18.85780795  5.32282563
   9.63591729]]
Нормализированный массив: [[-219.04992817 -279.79382269 -324.29984789 -228.28170237 -336.09360953
     0.          -30.03734784]
 [-141.6334989   -26.99601333  -22.01802945  -56.77226072 -110.51348976
  -347.71595742  -64.9814964 ]
 [-325.05257498   -8.00448003 -275.62757557 -150.26454434 -331.14960094
  -213.83950192 -300.87366213]
 [-292.56770071 -330.83010418  -92.56996117 -192.44244875 -338.11437724
   -92.40239744 -170.70159761]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [35]:
matrix = np.random.randint(0,11, (8,10))
row_index = np.argmin(np.sum(matrix, axis = 1))
min_sum_row = matrix[row_index]
print("Матрица: ",matrix)
print("Строка с мин суммой: ", min_sum_row)

Матрица:  [[ 4  8  4  9  5  6  3  2  6  2]
 [ 2  7 10  5  6  3  7  6  1  5]
 [ 3  7  9  9  7  0  6  4  5  6]
 [ 6  1  2  0  3  7  2  8  8  0]
 [ 0  9  5  1  5 10  2  3  8  8]
 [ 4  3  5  8  6  7  8  6  1  5]
 [ 9  7  6  3  6  4  8  3  5  0]
 [ 1  4  6  9  6  8  5  2  7  4]]
Строка с мин суммой:  [6 1 2 0 3 7 2 8 8 0]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [40]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

# Находим обратные матрицы A и B
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

# Вычисляем матрицу X
X = -np.dot(np.dot(A_inv, C), B_inv)

print("Матрица X:")
print(X)


Матрица X:
[[ 1.00000000e+00  1.11022302e-15]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [27]:
import numpy as np

a = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows =1, dtype='int32')
print(a[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [28]:

mean_values = np.mean(a[:, 1:], axis=0) #среднее

#  минимум
min_values = np.min(a[:, 1:], axis=0)

# макс
max_values = np.max(a[:, 1:], axis=0)

# медианы 
median_values = np.median(a[:, 1:], axis=0)

print("Среднее значение по каждому столбцу, кроме первого:", mean_values)
print("Минимум по каждому столбцу, кроме первого:", min_values)
print("Максимум по каждому столбцу, кроме первого:", max_values)
print("Медиана по каждому столбцу, кроме первого:", median_values)

Среднее значение по каждому столбцу, кроме первого: [2.16010017e+04 9.05528000e+00]
Минимум по каждому столбцу, кроме первого: [0 1]
Максимум по каждому столбцу, кроме первого: [2147483647         39]
Медиана по каждому столбцу, кроме первого: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [29]:
minutes_column = a[:,1:2]
block = np.clip(minutes_column,0,np.quantile(minutes_column, 0.75))
print(block)

[[60.]
 [25.]
 [10.]
 ...
 [65.]
 [ 5.]
 [65.]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [30]:
count = np.count_nonzero(a[:, 1]==0)
if count > 0:
    a[:, 1] = np.where(a[:, 1]== 0 , 1, a[:, 1])
print(count)

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [62]:
un_rcps = np.unique(a[:, 0])
num_un_rcps = len(un_rcps)
print(num_un_rcps)

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [31]:
ingr = np.unique(a[:, 2])
print(ingr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [32]:
print(a[a[:, 2]<= 5])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [84]:
ingr_min = a[:, 2]/a[:,1]
print(np.max(ingr_min))

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [33]:
top100_rcps = a[np.argsort(a[:, 1])[:: -1][:100]]
print(np.mean(top100_rcps[:, 2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [36]:
random_rcps = np.random.choice(a.shape[0], 10, replace=False)
for id in random_rcps:
    r_id, time, ingrs = a[id]
    print(f'id рецепта: {r_id}, время выполнения: {time}, кол-во рецептов: {ingrs}')

id рецепта: 469798, время выполнения: 195, кол-во рецептов: 7
id рецепта: 277766, время выполнения: 50, кол-во рецептов: 15
id рецепта: 119888, время выполнения: 160, кол-во рецептов: 3
id рецепта: 87308, время выполнения: 25, кол-во рецептов: 10
id рецепта: 432165, время выполнения: 22, кол-во рецептов: 7
id рецепта: 107114, время выполнения: 30, кол-во рецептов: 9
id рецепта: 344062, время выполнения: 20, кол-во рецептов: 8
id рецепта: 513673, время выполнения: 70, кол-во рецептов: 6
id рецепта: 59914, время выполнения: 50, кол-во рецептов: 20
id рецепта: 132809, время выполнения: 34, кол-во рецептов: 10


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [38]:
sr = np.mean(a[:, 2])
ings_mnsh_sr = a[a[:, 2] < sr]
print((len(ings_mnsh_sr) / len(a)) * 100) # в процентах 

58.802


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [39]:
simp_rcp = ((a[:, 1] <= 20) & (a[:, 2] <= 5)).astype(int)

data_with_simp_cl = np.column_stack((a, simp_rcp))
print(data_with_simp_cl[:10])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]
 [152828     40      7      0]
 [ 33941     18      9      0]
 [446597     15      5      1]
 [366174      7      9      0]
 [ 74205     20      7      0]]


13. Выведите процент "простых" рецептов в датасете

In [40]:
print(np.mean(simp_rcp) * 100, '%')

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [41]:
short_rcps = a[a[:, 1] < 10]
standard_rcps = a[(a[:, 1] >= 10) & (a[:, 1] < 20)]
long_rcps = a[a[:, 1] >= 20]

max_len = min(len(short_rcps), len(standard_rcps), len(long_rcps)) #максимальное кол-во рецептов в каждой группе

grouped_recipes = np.zeros((3, max_len, 3), dtype=int)
grouped_recipes[0, :len(short_rcps[:max_len])] = short_rcps[:max_len]
grouped_recipes[1, :len(standard_rcps[:max_len])] = standard_rcps[:max_len]
grouped_recipes[2, :len(long_rcps[:max_len])] = long_rcps[:max_len]

print(grouped_recipes)
print(grouped_recipes.shape)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [  4747      1      9]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
(3, 7588, 3)
